version: '1'
services:
  mysqldb:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: book_store
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: student
      MYSQL_PASSWORD: student
    restart: always
    networks:
      - issuetracker
    ports: 
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 20
    volumes:
      - datavolume:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: norbertsu/springboot-issuetracker:latest
    ports:
      - 8080:8080
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - issuetracker

networks:
  default:
    driver : 
      bridge
  issuetracker:
    name: issuetracker

volumes:
  datavolume: