name: Docker Build and Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - 'README.md'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysqldb:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: issue_tracker
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: tester
          MYSQL_PASSWORD: tester
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build JAR file
      run: mvn clean package -DskipTests

    - name: Build Docker image
      run: docker build -t norbertsu/springboot-issuetracker:latest .

    - name: Run Docker container (App)
      run: docker run --name app -p 8080:8080 -d norbertsu/springboot-issuetracker:latest

    - name: Run tests
      run: mvn test -Denvironment=pipeline

    - name: Stop and remove Docker container (App)
      if: always()
      run: |
        docker stop app
        docker rm app
